// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgWYTkzijl6edJXkaMUiBnC6GhWXSTtb8',
    appId: '1:631124301692:web:d3729cc4dd673b97e536f9',
    messagingSenderId: '631124301692',
    projectId: 'minimal-social-app-b73dc',
    authDomain: 'minimal-social-app-b73dc.firebaseapp.com',
    storageBucket: 'minimal-social-app-b73dc.appspot.com',
    measurementId: 'G-N3BQ3TFLNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-uJalz6xcQP-ORnSgTkd3Dvl2FLadCM',
    appId: '1:631124301692:android:75abbde93cdf0c53e536f9',
    messagingSenderId: '631124301692',
    projectId: 'minimal-social-app-b73dc',
    storageBucket: 'minimal-social-app-b73dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-KnIU_rfchfC99zZzJw_cdwvDSVl5PQA',
    appId: '1:631124301692:ios:cf786dfbcad13b27e536f9',
    messagingSenderId: '631124301692',
    projectId: 'minimal-social-app-b73dc',
    storageBucket: 'minimal-social-app-b73dc.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-KnIU_rfchfC99zZzJw_cdwvDSVl5PQA',
    appId: '1:631124301692:ios:738c6420930b1d48e536f9',
    messagingSenderId: '631124301692',
    projectId: 'minimal-social-app-b73dc',
    storageBucket: 'minimal-social-app-b73dc.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
