// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZhmkaRE3wVfPX0kK9aZj9bJpvah3fEg',
    appId: '1:839939325144:web:86cf596dbb63eef8e6ebad',
    messagingSenderId: '839939325144',
    projectId: 'social-app-97733',
    authDomain: 'social-app-97733.firebaseapp.com',
    storageBucket: 'social-app-97733.appspot.com',
    measurementId: 'G-R3WEXEK2QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvDamBbZj9to0WPxodLHHGJIMOAnQuSZ8',
    appId: '1:839939325144:android:0cd0ce9306b65f9fe6ebad',
    messagingSenderId: '839939325144',
    projectId: 'social-app-97733',
    storageBucket: 'social-app-97733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDasHro1Hv1nNaLfig5FSqmg_8TAYZ2Vi0',
    appId: '1:839939325144:ios:29bd99904bd8bc74e6ebad',
    messagingSenderId: '839939325144',
    projectId: 'social-app-97733',
    storageBucket: 'social-app-97733.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDasHro1Hv1nNaLfig5FSqmg_8TAYZ2Vi0',
    appId: '1:839939325144:ios:dee030fc5312aefce6ebad',
    messagingSenderId: '839939325144',
    projectId: 'social-app-97733',
    storageBucket: 'social-app-97733.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
